theme: jekyll-theme-minimal
name: Brendan Hasz
position: PhD Student in Neuroscience
github_url: https://github.com/brendanhasz
kaggle_url: https://www.kaggle.com/brendanhasz
linkedin_url: http://www.linkedin.com/in/brendan-hasz
email_url: mailto:winsto99@gmail.com
cv_url: /assets/files/BrendanHasz_CV.pdf
school_url: https://twin-cities.umn.edu/
place_url: https://www.google.com/maps/place/Minneapolis,+MN
school_name: University of Minnesota
place_name: Minneapolis, MN
