theme: jekyll-theme-minimal
markdown: kramdown
name: Brendan Hasz
position: PhD Student in Neuroscience
github_url: https://github.com/brendanhasz
kaggle_url: https://www.kaggle.com/brendanhasz
linkedin_url: http://www.linkedin.com/in/brendan-hasz
email_url: mailto:winsto99@gmail.com
cv_url: /assets/files/BrendanHasz_CV.pdf
resume_url: /assets/files/BrendanHasz_Resume.pdf
company_name: University of Minnesota
company_url: https://twin-cities.umn.edu/
place_name: Minneapolis, MN
title: Brendan Hasz
description: Blog
url: https://brendanhasz.github.io/
logo: /assets/img/headshot.jpg
social:
  links:
    - http://www.linkedin.com/in/brendan-hasz
    - https://github.com/brendanhasz
    - https://www.kaggle.com/brendanhasz
plugins:
  - jekyll-seo-tag
highlighter: rouge