theme: jekyll-theme-minimal
name: Brendan Hasz
github_url: https://github.com/brendanhasz
kaggle_url: https://www.kaggle.com/brendanhasz
linkedin_url: http://www.linkedin.com/in/brendan-hasz
email_url: mailto:winsto99@gmail.com
cv_url: /assets/files/BrendanHasz_CV.pdf
